//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAccionPersonal
    {
        public int Acp_Id { get; set; }
        public string Acp_Correlativo { get; set; }
        public int emp_Id { get; set; }
        public int Acp_JefeInmediato { get; set; }
        public System.DateTime Acp_FechaSolicitud { get; set; }
        public int tipmo_id { get; set; }
        public string Acp_Comentario { get; set; }
        public int est_Id { get; set; }
        public string Acp_RazonRechazo { get; set; }
        public Nullable<int> Acp_UsuarioCrea { get; set; }
        public System.DateTime Acp_FechaCrea { get; set; }
        public Nullable<int> Acp_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Acp_FechaModifica { get; set; }
    
        public virtual tbEstado tbEstado { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbTipoMovimiento tbTipoMovimiento { get; set; }
        public virtual tbEmpleado tbEmpleado1 { get; set; }
    }
}
