//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAnticipoSalario
    {
        public int Ansal_Id { get; set; }
        public string Ansal_Correlativo { get; set; }
        public int emp_Id { get; set; }
        public int Ansal_JefeInmediato { get; set; }
        public System.DateTime Ansal_GralFechaSolicitud { get; set; }
        public decimal Ansal_MontoSolicitado { get; set; }
        public int tpsal_id { get; set; }
        public string Ansal_Justificacion { get; set; }
        public string Ansal_Comentario { get; set; }
        public int est_Id { get; set; }
        public string Ansal_RazonRechazo { get; set; }
        public int Ansal_UsuarioCrea { get; set; }
        public System.DateTime Ansal_FechaCrea { get; set; }
        public Nullable<int> Ansal_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Ansal_FechaModifica { get; set; }
    
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbEmpleado tbEmpleado1 { get; set; }
        public virtual tbEstado tbEstado { get; set; }
        public virtual tbTipoSalario tbTipoSalario { get; set; }
    }
}
