//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBitacoraErrores
    {
        public int bite_Id { get; set; }
        public string bite_Controlador { get; set; }
        public string bite_Accion { get; set; }
        public string bite_Usuario { get; set; }
        public Nullable<System.DateTime> bite_Fecha { get; set; }
        public string bite_MensajeError { get; set; }
    }
}
