//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstitucionFinanciera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInstitucionFinanciera()
        {
            this.tbDeduccionInstitucionFinanciera = new HashSet<tbDeduccionInstitucionFinanciera>();
        }
    
        public int insf_Id { get; set; }
        public string insf_Nombre { get; set; }
        public string insf_Contacto { get; set; }
        public string insf_Telefono { get; set; }
        public string insf_Correo { get; set; }
        public bool insf_Activo { get; set; }
        public int insf_UsuarioCrea { get; set; }
        public System.DateTime insf_FechaCrea { get; set; }
        public Nullable<int> insf_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> insf_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDeduccionInstitucionFinanciera> tbDeduccionInstitucionFinanciera { get; set; }
    }
}
