//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLiquidacionAnticipoViatico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLiquidacionAnticipoViatico()
        {
            this.tbLiquidacionAnticipoViaticoDetalle = new HashSet<tbLiquidacionAnticipoViaticoDetalle>();
        }
    
        public int Lianvi_Id { get; set; }
        public string Lianvi_Correlativo { get; set; }
        public int Anvi_Id { get; set; }
        public System.DateTime Lianvi_FechaLiquida { get; set; }
        public System.DateTime Lianvi_FechaInicioViaje { get; set; }
        public System.DateTime Lianvi_FechaFinViaje { get; set; }
        public string Lianvi_Comentario { get; set; }
        public int est_Id { get; set; }
        public string Lianvi_RazonRechazo { get; set; }
        public int Lianvi_UsuarioCrea { get; set; }
        public System.DateTime Lianvi_FechaCrea { get; set; }
        public Nullable<int> Lianvi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Lianvi_FechaModifica { get; set; }
    
        public virtual tbAnticipoViatico tbAnticipoViatico { get; set; }
        public virtual tbEstado tbEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLiquidacionAnticipoViaticoDetalle> tbLiquidacionAnticipoViaticoDetalle { get; set; }
    }
}
