//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProducto()
        {
            this.tbRequisionCompraDetalle = new HashSet<tbRequisionCompraDetalle>();
        }
    
        public int prod_Id { get; set; }
        public string prod_Codigo { get; set; }
        public string prod_CodigoBarras { get; set; }
        public string prod_Descripcion { get; set; }
        public string prod_Marca { get; set; }
        public string prod_Modelo { get; set; }
        public string prod_Talla { get; set; }
        public string prod_Color { get; set; }
        public int pscat_Id { get; set; }
        public int uni_Id { get; set; }
        public int prov_Id { get; set; }
        public bool prod_EsActivo { get; set; }
        public string prod_RazonInactivacion { get; set; }
        public int prod_UsuarioCrea { get; set; }
        public System.DateTime prod_FechaCrea { get; set; }
        public Nullable<int> prod_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> prod_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRequisionCompraDetalle> tbRequisionCompraDetalle { get; set; }
        public virtual tbUnidadMedida tbUnidadMedida { get; set; }
        public virtual tbProductoSubcategoria tbProductoSubcategoria { get; set; }
        public virtual tbProveedor tbProveedor { get; set; }
    }
}
