//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRequisionCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbRequisionCompra()
        {
            this.tbRequisionCompraDetalle = new HashSet<tbRequisionCompraDetalle>();
        }
    
        public int Reqco_Id { get; set; }
        public string Reqco_Correlativo { get; set; }
        public int emp_Id { get; set; }
        public int are_Id { get; set; }
        public System.DateTime Reqco_GralFechaSolicitud { get; set; }
        public string Reqco_Comentario { get; set; }
        public int est_Id { get; set; }
        public string Reqco_RazonRechazo { get; set; }
        public int Reqco_UsuarioCrea { get; set; }
        public System.DateTime Reqco_FechaCrea { get; set; }
        public Nullable<int> Reqco_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> Reqco_FechaModifica { get; set; }
    
        public virtual tbArea tbArea { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbEstado tbEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRequisionCompraDetalle> tbRequisionCompraDetalle { get; set; }
    }
}
