//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSolicitudReembolsoGastosDetalle
    {
        public int ReemgaDet_Id { get; set; }
        public int Reemga_Id { get; set; }
        public System.DateTime ReemgaDet_FechaGasto { get; set; }
        public int tpv_Id { get; set; }
        public decimal ReemgaDet_MontoGasto { get; set; }
        public string ReemgaDet_Concepto { get; set; }
        public string ReemgaDet_Archivo { get; set; }
    
        public virtual tbSolicitudReembolsoGastos tbSolicitudReembolsoGastos { get; set; }
        public virtual tbTipoViatico tbTipoViatico { get; set; }
    }
}
