//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSueldo
    {
        public int sue_Id { get; set; }
        public int emp_Id { get; set; }
        public Nullable<decimal> sue_Cantidad { get; set; }
        public short tmo_Id { get; set; }
        public int sue_UsuarioCrea { get; set; }
        public Nullable<System.DateTime> sue_FechaCrea { get; set; }
        public Nullable<int> sue_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> sue_FechaModifica { get; set; }
    
        public virtual tbMoneda tbMoneda { get; set; }
        public virtual tbMoneda tbMoneda1 { get; set; }
        public virtual tbEmpleado tbEmpleado { get; set; }
        public virtual tbEmpleado tbEmpleado1 { get; set; }
    }
}
