//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTipoTransporte()
        {
            this.tbAnticipoViatico = new HashSet<tbAnticipoViatico>();
        }
    
        public int tptran_Id { get; set; }
        public string tptran_Descripcion { get; set; }
        public int tptran_UsuarioCrea { get; set; }
        public System.DateTime tptran_FechaCrea { get; set; }
        public Nullable<int> tptran_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tptran_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAnticipoViatico> tbAnticipoViatico { get; set; }
    }
}
