//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoSangre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTipoSangre()
        {
            this.tbEmpleado = new HashSet<tbEmpleado>();
        }
    
        public int tps_Id { get; set; }
        public string tps_Descripcion { get; set; }
        public int tps_UsuarioCrea { get; set; }
        public System.DateTime tps_FechaCrea { get; set; }
        public Nullable<int> tps_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tps_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleado> tbEmpleado { get; set; }
    }
}
